### ISSUE TITLE
Maven package

### ISSUE THREAD

**Issue by fabianmenges** [google/zetasketch#1]
Are you planning on releasing an official maven package/artifact?

**Comment by robinyqiu** [comment]
Yes we are working on that. Thanks for your interest! I will update and close this issue when the first version of the artifact is available in Maven Central. Please note that the first release will be a "beta" version.

**Comment by robinyqiu** [comment]
ZetaSketch 0.1.0 (a beta version) is released to Maven Central:
http://repo1.maven.org/maven2/com/google/zetasketch/zetasketch/0.1.0/

**Comment by fabianmenges** [comment]
Thanks!
