### ISSUE TITLE
[question] Is this optimization valid?

### ISSUE THREAD

**Issue by travis-madhive** [google/zetasketch#8]
Is this optimization valid? If I understand correctly, Java arrays are objects, and therefore wouldn't be boxed.

https://github.com/google/zetasketch/blob/a2f2692fae8cf61103330f9f70e696c4ba8b94b0/java/com/google/zetasketch/HyperLogLogPlusPlus.java#L188-L197

**Comment by robinyqiu** [comment]
I believe "boxing" here does not refer to the Java autoboxing (e.g. int -> Integer). It means that caller of `add()` can call this function directly if they have a `byte[]` ready, instead of calling `add(Object)` which they have to box `byte[]` into `ByteString`.

**Comment by travis-madhive** [comment]
Ah, I see. Okay, thanks for the quick response!
